name: Validate Docker Compose on Dev

on:
  push:
    branches:
      - dev

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Debug - Check working directory
      - name: List project files
        run: ls -R .

      # Step 4: Run Docker Compose (up and down)
      - name: Test Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      # Step 5: Verify services
      - name: Verify services
        run: |
          docker-compose ps
          docker-compose exec <service-name> echo "Service is running"

      # Step 6: Clean up services
      - name: Clean up services
        run: docker-compose down --volumes
